export interface ToolResult {
  success: boolean;
  data?: unknown;
  error?: string;
}

export function toolCallLabel(name: string, input: Record<string, any>): string {
  const labels: Record<string, () => string> = {
    get_account_overview:    () => "Fetching account performance overview…",
    get_breakdown:           () => `Fetching ${String(input.breakdown ?? "").replace(/_/g, " ")} breakdown…`,
    get_daily_insights:      () => "Loading daily performance trends…",
    get_account_info:        () => "Fetching account balance & info…",
    get_campaigns:           () => "Loading all campaigns with insights…",
    create_campaign:         () => `Creating campaign: ${input.name}`,
    pause_campaign:          () => `Pausing campaign: ${input.campaign_name}`,
    enable_campaign:         () => `Enabling campaign: ${input.campaign_name}`,
    set_campaign_budget:     () => `Updating budget for: ${input.campaign_name}`,
    delete_campaign:         () => `Deleting campaign: ${input.campaign_name}`,
    duplicate_campaign:      () => `Duplicating campaign: ${input.campaign_name}`,
    set_spend_cap:           () => `Setting account spend cap to ${input.spend_cap}…`,
    get_adsets:              () => input.campaign_id ? `Loading ad sets for campaign ${input.campaign_id}…` : "Loading all ad sets…",
    create_adset:            () => `Creating ad set: ${input.name}`,
    pause_adset:             () => `Pausing ad set: ${input.adset_name}`,
    enable_adset:            () => `Enabling ad set: ${input.adset_name}`,
    set_adset_budget:        () => `Updating budget for: ${input.adset_name}`,
    delete_adset:            () => `Deleting ad set: ${input.adset_name}`,
    get_ads:                 () => input.adset_id ? `Loading ads for ad set ${input.adset_id}…` : "Loading all ads…",
    create_ad:               () => `Creating ad: ${input.name}`,
    pause_ad:                () => `Pausing ad: ${input.ad_name}`,
    enable_ad:               () => `Enabling ad: ${input.ad_name}`,
    delete_ad:               () => `Deleting ad: ${input.ad_name}`,
    get_adcreatives:         () => "Loading all ad creatives…",
    create_adcreative:       () => `Creating creative: ${input.name}`,
    delete_adcreative:       () => `Deleting creative: ${input.creative_name}`,
    get_customaudiences:     () => "Loading all custom audiences…",
    create_lookalike:        () => `Creating lookalike audience: ${input.name}`,
    create_customaudience:   () => `Creating audience: ${input.name}`,
    delete_customaudience:   () => `Deleting audience: ${input.audience_name}`,
    get_adimages:            () => "Loading all ad images…",
    upload_adimage_by_url:   () => `Uploading image: ${input.name}`,
    delete_adimage:          () => `Deleting image hash: ${input.image_hash}`,
    get_advideos:            () => "Loading all ad videos…",
    delete_advideo:          () => `Deleting video: ${input.video_title}`,
    get_adspixels:           () => "Loading all pixels…",
    create_adspixel:         () => `Creating pixel: ${input.name}`,
    get_pixel_stats:         () => `Fetching stats for pixel ${input.pixel_id}…`,
    get_adrules:             () => "Loading all ad rules…",
    create_adrule:           () => `Creating rule: ${input.name}`,
    enable_adrule:           () => `Enabling rule: ${input.rule_name}`,
    disable_adrule:          () => `Disabling rule: ${input.rule_name}`,
    delete_adrule:           () => `Deleting rule: ${input.rule_name}`,
    get_customconversions:   () => "Loading all custom conversions…",
    create_customconversion: () => `Creating conversion: ${input.name}`,
    delete_customconversion: () => `Deleting conversion: ${input.conversion_name}`,
    get_productcatalogs:     () => "Loading all product catalogs…",
    get_catalog_products:    () => `Loading products in catalog ${input.catalog_id}…`,
    delete_catalog_product:  () => `Deleting product ${input.product_name} from catalog…`,
    save_account_brain:         () => "Saving account intelligence to memory…",
    execute_campaign_template:  () => `Executing ${String(input.template ?? "").replace(/_/g, " ")} template…`,
  };
  return labels[name]?.() ?? `Running ${name}…`;
}

export function toolDoneLabel(name: string, input: Record<string, any>, result: ToolResult): string {
  if (!result.success) return `Failed: ${result.error ?? "unknown error"}`;
  const count = (result.data as any)?.data?.length as number | undefined;
  const doneLabels: Record<string, () => string> = {
    get_account_overview:    () => "Account overview loaded",
    get_breakdown:           () => `${String(input.breakdown ?? "").replace(/_/g, " ")} breakdown loaded`,
    get_daily_insights:      () => count != null ? `${count} days of data loaded` : "Daily data loaded",
    get_account_info:        () => "Account info loaded",
    get_campaigns:           () => count != null ? `${count} campaigns loaded` : "Campaigns loaded",
    create_campaign:         () => `Campaign "${input.name}" created`,
    pause_campaign:          () => `Campaign "${input.campaign_name}" paused`,
    enable_campaign:         () => `Campaign "${input.campaign_name}" enabled`,
    set_campaign_budget:     () => `Budget set to ${input.daily_budget} for "${input.campaign_name}"`,
    delete_campaign:         () => `Campaign "${input.campaign_name}" deleted`,
    duplicate_campaign:      () => `Campaign "${input.campaign_name}" duplicated`,
    set_spend_cap:           () => input.spend_cap === 0 ? "Spend cap removed" : `Spend cap set to ${input.spend_cap}`,
    get_adsets:              () => count != null ? `${count} ad sets loaded` : "Ad sets loaded",
    create_adset:            () => `Ad set "${input.name}" created`,
    pause_adset:             () => `Ad set "${input.adset_name}" paused`,
    enable_adset:            () => `Ad set "${input.adset_name}" enabled`,
    set_adset_budget:        () => `Budget set to ${input.daily_budget} for "${input.adset_name}"`,
    delete_adset:            () => `Ad set "${input.adset_name}" deleted`,
    get_ads:                 () => count != null ? `${count} ads loaded` : "Ads loaded",
    create_ad:               () => `Ad "${input.name}" created`,
    pause_ad:                () => `Ad "${input.ad_name}" paused`,
    enable_ad:               () => `Ad "${input.ad_name}" enabled`,
    delete_ad:               () => `Ad "${input.ad_name}" deleted`,
    get_adcreatives:         () => count != null ? `${count} creatives loaded` : "Creatives loaded",
    create_adcreative:       () => `Creative "${input.name}" created`,
    delete_adcreative:       () => `Creative "${input.creative_name}" deleted`,
    get_customaudiences:     () => count != null ? `${count} audiences loaded` : "Audiences loaded",
    create_lookalike:        () => `Lookalike audience "${input.name}" created`,
    create_customaudience:   () => `Audience "${input.name}" created`,
    delete_customaudience:   () => `Audience "${input.audience_name}" deleted`,
    get_adimages:            () => count != null ? `${count} images loaded` : "Images loaded",
    upload_adimage_by_url:   () => `Image "${input.name}" uploaded`,
    delete_adimage:          () => `Image ${input.image_hash} deleted`,
    get_advideos:            () => count != null ? `${count} videos loaded` : "Videos loaded",
    delete_advideo:          () => `Video "${input.video_title}" deleted`,
    get_adspixels:           () => count != null ? `${count} pixels loaded` : "Pixels loaded",
    create_adspixel:         () => `Pixel "${input.name}" created`,
    get_pixel_stats:         () => "Pixel stats loaded",
    get_adrules:             () => count != null ? `${count} rules loaded` : "Rules loaded",
    create_adrule:           () => `Rule "${input.name}" created`,
    enable_adrule:           () => `Rule "${input.rule_name}" enabled`,
    disable_adrule:          () => `Rule "${input.rule_name}" disabled`,
    delete_adrule:           () => `Rule "${input.rule_name}" deleted`,
    get_customconversions:   () => count != null ? `${count} conversions loaded` : "Conversions loaded",
    create_customconversion: () => `Conversion "${input.name}" created`,
    delete_customconversion: () => `Conversion "${input.conversion_name}" deleted`,
    get_productcatalogs:     () => count != null ? `${count} catalogs loaded` : "Catalogs loaded",
    get_catalog_products:    () => count != null ? `${count} products loaded` : "Products loaded",
    delete_catalog_product:  () => `Product "${input.product_name}" deleted`,
    save_account_brain:         () => "Account intelligence saved to memory",
    execute_campaign_template:  () => {
      const r = result.data as any;
      if (r?.campaign_id) return `Campaign created (ID: ${r.campaign_id}) — ${r.adsets_created ?? 0} ad set(s) created`;
      return "Campaign template executed";
    },
  };
  return doneLabels[name]?.() ?? "Done";
}
